//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSv2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMS_DBEntities : DbContext
    {
        public HMS_DBEntities()
            : base("name=HMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<PatientTable> PatientTable { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Billing> Billing { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Physician> Physician { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
